FROM python:3.11

WORKDIR /app
ENV PYTHONPATH=/app
COPY requirements-worker.txt /app/
RUN pip install --no-cache-dir --upgrade pip && pip install --no-cache-dir -r requirements-worker.txt

COPY . /app/

CMD ["python", "workers/worker.py"]
